apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: spring-app
spec:
  selector:
    app: spring-app
  ports:
    - port: 5555
      targetPort: 5555
      name: http
      protocol: TCP
  type: LoadBalancer