apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-deployment
spec:
  selector:
    app: redis-deployment
  ports:
    - port: 6379
      targetPort: 6379
  type: LoadBalancer